### ISSUE TITLE
Test conda build in rocky linux

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#100]
#### Description
Currently the conda package tests are made on the runners provided by Github. Since khiops core supports rocky linux we should test also the conda installation in those systems.

#### Questions/Ideas
- Probably we need a container.
  - How does that play with the current workflow which uses no containers ?

**Comment by popescu-v** [comment]
IMHO, we should also build the Conda packages on Rocky Linux (8 and/or 9). Or rather, in a similar vein to what it is done for the currently-supported OSes, build the Conda packages on Rocky 8, and test them on Rocky 8 and Rocky 9.

**Comment by popescu-v** [comment]
For the container issue, IMHO, at first glance, the simplest approach would be to have different jobs for Rocky, in the same Conda build / test workflow, viz.:
-  `build-conda-package-on-rocky`, which would use the `image`(s) of the Rocky container,
- `build-conda-package`as of now, which runs on the matrix of natively-supported GitHub runner OSes.
- `test-conda-package-on-rocky`, which would test the Conda package on the images of the Rocky container
- `test-conda-package`, which runs as of now (matrix of natively-supported OSes).

AFAIU, the upload / download artifacts normally works in containers as well.

**Comment by folmos-at-orange** [comment]
I don't think it is necessary to build in rocky because conda packages are created and installed in an "closed environment".

The test should be the same as in the other but run in a rocky image with conda installed.

**Comment by popescu-v** [comment]
Well, as we build Khiops as part of the Conda package building, I think we need to make sure that everything works well end-to-end. In particular, the interaction between run-time dependencies of Khiops (DLLs, which are not exactly the same as on Debian/Ubuntu, cf. `ldd $(which MODL)` etc) and the changes Conda does to the binaries.

**Comment by folmos-at-orange** [comment]
We do not need to test the conda build in rocky. It should be independent of the linux distribution + arch. There are no "rocky" conda packages. We should build once in Ubuntu, and check that there are no problems in rocky, because that is what is going to be released.

**Comment by popescu-v** [comment]
Well, Rocky 8(.9) kernels are quite old (4.*) wrt. Ubuntu (even 20.04) kernels (5.*), so this might yield some libc incompatibilities? Or do we test only on Rocky 9 (kernels 5.14)? Otherwise, only Ubuntu 18.04 had 4.* kernels, but it is no longer supported. Rocky 8.9 is still supported, though.

**Comment by folmos-at-orange** [comment]
Is this solved with #127 ? @popescu-v

**Comment by popescu-v** [comment]
> Is this solved with #127 ? @popescu-v

IMHO, no, because #127 solved the system-wide + Pip installation case. This issue pertains to the Conda case. IMHO, it's mostly a CI issue, namely, to add rocky9 to the build-conda-package & test-conda-package jobs in the build-conda-package.yml workflow.

**Comment by folmos-at-orange** [comment]
Obsoleted by #152.
