### ISSUE TITLE
Accept DataFrame as target in sklearn estimators

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#120]
#### Description
Currently the `y` target parameter of the `.fit` method in supervised estimators accepts only `numpy.ndarray` or `pandas.Series`. It should accept also `pandas.DataFrames` provided that they are 1 dimensional

#### Questions/Ideas
- Since we already use `sklearn.utils.validation.column_or_1d` for the data validation of sklearn the fix consist only in expanding the type range accepted by `.fit(X,y)`.

**Comment by popescu-v** [comment]
I think this is +/- the same as https://github.com/KhiopsML/khiops-python/issues/75, right?

**Comment by folmos-at-orange** [comment]
Duplicate of #75
