### ISSUE TITLE
Support fouth digit in version scheme

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#133]
#### Description
The new versioning scheme is that khiops `MAJOR.MINOR.PATH` with an correlative `.KP_INCREMENT`. We must update the versioning class to support this scheme.

#### Questions/Ideas
- TBD

**Comment by popescu-v** [comment]
In order to be compatible with `versioneer` which supports PEP 440, one will use a fourth number after a dot, like: `major.minor.patch.extra`, where `extra` denotes 0-versioned khiops-python versions, based on Khiops `major.minor.patch`.
