### ISSUE TITLE
Run unittest for every supported python version.

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#152]
#### Description
Currently, we only run the unittests for python 3.10. We should do it for every python version supported (3.8 -> 3.12).

#### Questions/Ideas
- Add miniconda to the dev docker with 5 envs (one for each python) and mpich installed.
- Remove from the dev docker mpich system-wide installation 
- Make the python version a matrix in the CI

**Comment by popescu-v** [comment]
IMHO, we should also keep the out-of-Conda-environment tests (and the system-wide MPICH), in order to keep testing the `KhiopsLocalRunner` behaviour on genuine system-wide installations (especially wrt. MPI detection integration tests).

**Comment by folmos-at-orange** [comment]
> IMHO, we should also keep the out-of-Conda-environment tests (and the system-wide MPICH), in order to keep testing the `KhiopsLocalRunner` behaviour on genuine system-wide installations (especially wrt. MPI detection integration tests).

Right, then we should have the following variants of `khiopspydev`:
- For systemwide the following OSs: `rocky8`, `rocky9`, `ubuntu22.04`, `ubuntu20.04`
- For conda: `conda-py38`, `conda-py39`, `conda-py310`, `conda-py311`, `conda-py312`
