### ISSUE TITLE
Find a workaround for Rocky 8

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#157]
#### Description
Currently, `khiops-python` doesn't work in Rocky 8. This is because the default python there is 3.6. We should find a workaround to support it.

#### Questions/Ideas
Options
- Make a fallback strategy for the `modules` part of the runner
- Make it work by calling bash
- Propose an installation for Khiops > `3.8`.

**Comment by popescu-v** [comment]
Related issue: #154

**Comment by popescu-v** [comment]
Possible resolution strategies:
1/ use current strategy; if it fails (i.e. no `mpiexec` detected), then fallback to Sh/Bash (check `modules.sh` exists)
2/ directly use Shell-based environment module loading.

**Comment by popescu-v** [comment]
> Possible resolution strategies: 1/ attempt to use current strategy first; if it fails (i.e. no `mpiexec` detected), then fallback to Sh/Bash (check `modules.sh` exists) 2/ directly use Shell-based environment module loading.

The second strategy was adopted, as it is more portable and needs less complex code.
