### ISSUE TITLE
Implement multi-table helper functions

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#171]
#### Description
Implement with the current multi-table interface of sklearn the functions:
- `sort_ds(ds_spec, engine="default", **kwargs)`
 - Sorts a dataset tables by their keys
- `train_test_split_ds(ds_spec, **kwargs)`
 - Splits in train/test a dataset

#### Questions/Ideas
- Refactor dataset spec checks
- Undeprecate FileDatasets.
- Update tutorials.

**Comment by folmos-at-orange** [comment]
Re-spec after meeting 18/09:
- Only keep `train_test_split_dataset` for dataframes
- Redeprecate File datasets

**Comment by popescu-v** [comment]
Done in PR https://github.com/KhiopsML/khiops-python/pull/180.
