### ISSUE TITLE
Check in CICD that the MPI args are the same as khiops-env

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#174]
#### Description
To be sure that we have the same MPI settings as the native khiops installations we should implement a small check in the CICD for that.

#### Questions/Ideas
- Where: `Unit Tests` or `Conda Package` ?
- Only Windows and Linux are concerned.

**Comment by popescu-v** [comment]
IMHO this should be in the `Unit Tests` workflow, as there we have the system-wide package which contains `khiops-env`.

**Comment by popescu-v** [comment]
No longer relevant, following PRs:
- https://github.com/KhiopsML/khiops-python/pull/252: the Khiops Python library now reads the MPI settings directly from `khiops_env`
- https://github.com/KhiopsML/khiops-python/pull/261: more extensive integration tests have been added, for most supported platforms.
