### ISSUE TITLE
Add conditional code to handle workaround for sparse tables

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#178]
#### Description
When solving the issue #42 we had to make a workaround for writing sparse tables with empty lines. The bug requiring the workaround will be fixed in a upcoming Khiops version (https://github.com/KhiopsML/khiops/issues/235). When that lands we should have a conditional code on the khiops version to whether apply or not the workaround. This is to support all 10.x.x series.

#### Questions/Ideas
- Since is a critical part of the code we should be able to plug the function that writes a sparse row instead of testing the version for each row.
- In stand-by until the fix for khiops-core lands.

**Comment by folmos-at-orange** [comment]
Note that it has been decided that `khiops-python` 11 will support only Khiops 11. So the issue is now to change the code for the upcoming version 11.

**Comment by popescu-v** [comment]
This could also be implemented for `10.2.3.X` versions, as since 10.2.3 there is the breaking change of relying on the novel `khiops_env` script anyway.

**Comment by folmos-at-orange** [comment]
This was already solved in 39490a59cdb0ab6. I think we can close this safely.

**Comment by popescu-v** [comment]
> This was already solved in [39490a5](https://github.com/KhiopsML/khiops-python/commit/39490a59cdb0ab6dd827079397fba3abcb89297f). I think we can close this safely.

Indeed, it was solved just after the upstream Khiops core issue https://github.com/KhiopsML/khiops/issues/235 has been fixed by PR https://github.com/KhiopsML/khiops/pull/241.

So, I'm closing and obsoleting this issue.
