### ISSUE TITLE
Installation Issue on macOS with Python 3.12

### ISSUE THREAD

**Issue by lucaurelien** [KhiopsML/khiops-python#184]
Hello,

A user is facing an issue while trying to install Khiops on macOS with Python 3.12 installed via Conda. Here's a detailed description of the problem:

**Environment:**
- **Operating System:** macOS (**ARM**)
- **Python Version:** 3.12 (installed via Conda)
- **Conda Channels:** conda-forge, khiops

**Issue Description:**
The user tried to install Khiops using the following command:
```sh
conda install -c conda-forge -c khiops khiops
```
However, the user encountered the following error:
```sh
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package khiops-10.2.0.0-py312hcb8d3e5_0 requires python_abi 3.12.* *_cp312, but none of the providers can be installed
```

**Additional Information:**
- `python --version`: Python 3.12.2
- `which python`: /Users/nicolasschlewitz/.local/miniconda3/bin/python
- `which conda`: 
```sh
conda () {
    \local cmd="${1-__missing__}"
    case "$cmd" in
        (activate | deactivate) __conda_activate "$@" ;;
        (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
        __conda_reactivate ;;
        (*) __conda_exe "$@" ;;
    esac
}
```
- `env | grep -i path`:
```sh
PATH=/Users/nicolasschlewitz/.local/miniconda3/bin:/Users/nicolasschlewitz/.local/miniconda3/condabin:/Users/nicolasschlewitz/google-cloud-sdk/bin:/opt/homebrew/bin:/Users/nicolasschlewitz/.local/bin:/Users/nicolasschlewitz/.rd/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/munki:/usr/local/munkireport
```

**Possible Incompatibilities:**
- The Khiops package requires `python_abi 3.12.* *_cp312`, but this seems to be causing conflicts with other dependencies.

**Comment by popescu-v** [comment]
From the issue description, it seems that the installation of the Khiops package from the `conda-forge` channel has been attempted in the `base` Conda environment.

Could one try to install Khiops inside a new Conda environment?

Indeed, Conda-forge maintainers recommend to always install packages from conda-forge inside a new environment that is different from the `base` Conda environment:
- https://conda-forge.org/docs/user/introduction/
- https://conda-forge.org/docs/user/tipsandtricks/

Consequently, one could update the doc accordingly IMHO.

**Comment by popescu-v** [comment]
Closing, this is a documentation issue for the time being: https://github.com/KhiopsML/khiops-doc/issues/35.
