### ISSUE TITLE
Use conda forge to build package

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#189]
#### Description
For details see https://github.com/KhiopsML/pilotage/issues/13

#### Questions/Ideas
- Eliminate the `default` channel from the builds and tests
- Use only `conda-forge` and `khiops-dev`/`khiops` for build and tests

**Comment by popescu-v** [comment]
Investigate using Miniforge (https://github.com/conda-forge/miniforge) instead of Miniconda?

**Comment by folmos-at-orange** [comment]
StandBy: Waiting for https://github.com/KhiopsML/khiops/pull/341
