### ISSUE TITLE
Add function to open the external visualization tool

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#195]
#### Description
While waiting for the visualization widget #90, add a simple function to open a (co)visualization report file.

#### Questions/Ideas
- Code
```python
import os
import platform

def os_open(path):
    """Opens a file or directory with its default application, prints a message on failure"""
    try:
        if platform.system() == "Windows":
            os.startfile(path)
        elif platform.system() == "Darwin":
            subprocess.call(["open", path])
        else:
            subprocess.call(["xdg-open", path])
    except OSError as error:
        print("Could not open report file {error}. Path: {path}")
```
- Test manually, test in CI optional.
- Change the Tutorials so they use this function instead of the locally defined one.

**Comment by popescu-v** [comment]
Perhaps also add a dedicated sklearn helper, like `show_report` which takes a fitted estimator as a parameter and calls `os_open` to show the report? Thus, the user need not look-up the report; this would be transparent.

**Comment by folmos-at-orange** [comment]
Yes, I'm ok with `show_report` in sklean estimators (the only minor issue is that we will have to write an ugly temporary file). Maybe we should call `show_report` all the functions even though they do much more.

With respect to the fallback I'm ok as well.

**Comment by folmos-at-orange** [comment]
In the weekly it was settled to call the function `visualize_report`.
