### ISSUE TITLE
Inventory Khiops Type Coercion Cases and Implement Sklearn-Side Policy Accordingly

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#232]
#### Description
Currently, in estimator methods like `_check_dictionary_compatibility`, numerical types are coerced to categorical types.
However, other type incompatibilities are not coerced and error is raised.
One needs to check whether other coercion cases are possible, viz.:
- among the Date / Time / Timestamp types

**Comment by folmos-at-orange** [comment]
Possibli not a problem.

**Comment by popescu-v** [comment]
This is already handled inherently.
