### ISSUE TITLE
Simplify API to set/get max core number and memory limit

### ISSUE THREAD

**Issue by marcboulle** [KhiopsML/khiops-python#257]
#### Description
Actuellement, j'ai toujours du mal à trouver comment modifier ces paramètres en me basant sur la doc sur le site API Docs.
Il semble que l'on passe par des variables, mais ce n'est pas clair, cela semble interne.
En cherchant "max_core", on tombe sur
[khiops.core.internals.runner.KhiopsRunner.max_cores](https://khiopsml.github.io/khiops-python/internal/generated/khiops.core.internals.runner.html#khiops.core.internals.runner.KhiopsRunner.max_cores) (Python property, in core.internals.runner)

Une API basique à partir de set/get me semblerait plus simple à utiliser, et pourrait être documentée directement parmi les fonction core (au même niveau que get_khiops_version).
Une solution encore plus "naturelle" serait de traiter les paramètres de type `max_core_number` et `memory_limit` au même titre que les paramètres d'aide à la mise au point (`trace`, `log_file_path`, `output_scenario_path`), dans les __Common Parameters__:
- paramètres optionnels des fonctions de l'API core
- example de type `train_predictor_ressource_limits`, au même titre que l'example `train_predictor_error_handling`

Autre remarque au passage sur la doc : référence obsolète à la license
- get_khiops_coclustering_info : Returns the Khiops Coclustering license information
- get_khiops_info : Returns the Khiops license information

**Comment by popescu-v** [comment]
Related to https://github.com/KhiopsML/khiops-python/issues/263

**Comment by popescu-v** [comment]
Subsumed by #258, #263 and #264. Hence, this will also be closed by PR #296 as soon as it is finalized.
