### ISSUE TITLE
Limit Exposure of `khiops_env` Details in the Khiops Python Library Public API and Documentation

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#258]
#### Description
Currently, the `KHIOPS_PROC_NUMBER` and `KHIOPS_MEMORY_LIMIT` are:
- documented in the `KhiopsLocalRunner` docstring and the `doc/notes.rst` file
- publicly exposed as the `max_cores` and `max_memory_mb` read-only attributes / properties of `KhiopsLocalRunner`
- used, via the aforementioned attributes, in the `kh-status` command.

#### Questions/Ideas
- A first solution is to:
  - stop documenting these variables altogether
  - stop exposing them as public read-only attributes of the local runner
- However, the drawback of this approach is that the Python integrator would have no documented way of tweaking these settings.

- Another solution is to provide an "advanced" API which would allow to:
   - also mutate these settings (so the properties would not be read-only anymore)
   - as this has implications on other settings (mutating `max_cores` would change the MPI command in `KHIOPS_MPI_COMMAND`), once one of these settings is mutated, the corresponding environment variables should be updated in the environment accordingly, then the `khiops_env` script re-run.
- This solution seems more complex, but it would allow full control from the Python side of these settings (as a direct client / user of `khiops_env` has).

**Comment by marcboulle** [comment]
On a deux type d'utilisateur différents:
- les data scientist, qui sont nos seuls utilisateurs externes, pour lesquels on vise des services les plus simple possible à utiliser
- les intégrateurs, qui sont essentiellement des développeurs internes Orange, et qui ne sont pas notre cible

Pour les data scientist
- on ne doit présenter que les fonctionnalités utiles, en ayant une documentation la plus simple possible, masquant au mieux tous les aspect intégration
- la nécessité de tweaker la partie intégration est inexistante, et ces aspects ne doivent pas être documentés

Pour les intégrateurs
- on passe maintenant par khiops_env, qui est explicitement défini comme _internal_
  cf. `khiops_env is an internal script intended to be used by Khiops tool and Khiops wrappers only.`
- ce script est auto-documenté
- si cette doc ne suffit pas, on peut rajouter un wiki sur le github KhiopsML/khiops
- c'est le seul endroit utilisable pour tweeker l'intégration, via les variables d'environnement utilisées dans le script
  - tout double maintenance (par exemple depuis pykhiops) est à éviter

On peut affiner légèrement ce public d'intégrateur
- intégration professionnelle de niveau _produit_, diffusé officiellement sur le site
  - uniquement intégrateurs internes Orange
  - pykhiops, AutoML, docker, notebook...
- intégration légère pour les utilisateurs externes
  - cible: intégration rapide pour utilisation de Khiops depuis C++, Java, Java script, MATLAB, R…
  - pas de livraison de niveau produit, pas de maintenance
  - dans ce cas, on passe par les script de lancement khiops et khiops_coclustering, sans aucune référence à khiops_env
  - tout passe par la gestion des scénarios, et c'est documenté officiellement
  cf. `For easy system integration:
    [Khiops Scenarios](https://khiops.org/setup/KhiopsScenarios-v10.2.0.pdf), based on recording and replaying Khiops scenarios in batch mode from any programming language.`

**Comment by popescu-v** [comment]
OK then for:

- in the Khiops Python library (aimed especially at data scientists or at what we could call "high-level users" that just use the Python library in other software components):
   - undocumenting `KHIOPS_PROC_NUMBER` and `KHIOPS_MEMORY_LIMIT`
   - not exposing `khiops_env`-derived details in the Python library; namely, the following `KhiopsLocalRunner` attributes could no longer be publicly exposed:
      - `max_cores` [read-only] (set from `KHIOPS_PROC_NUMBER`)
      - `max_memory_mb` [read-only] (set from `KHIOPS_MEMORY_LIMIT`)
      - `mpi_command_args` [read-only] (set from `KHIOPS_MPI_COMMAND`)
      - `khiops_path` [read-write] (set from `KHIOPS_PATH`)
      - `khiops_coclustering_path` (set from `KHIOPS_COCLUSTERING_PATH`)

- on the Wiki of the `khiops` GitHub repo:
   - mention `khiops_env` (and its `--help` output), aimed at product-level integration
   - mention `khiops` / `khiops_coclustering` plus the scenarios-based approach (`khiops -b -i ...` / `khiops_coclustering -b -i ...`), aimed at lightweight (language-independent) integration

- perhaps an "Advanced" section on the official website (issue for the `khiops-doc` GitHub repo), where we would mention (perhaps with a slightly different, more verbose rephrasing) the same approaches as on the Wiki of the `khiops` repo.
