### ISSUE TITLE
Scenarios' `MaxCoreNumber`, `MemoryLimit` and `TemporaryDirectoryName` `AnalysisSpec.SystemParameters` Are Set via Environment-set Values

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#263]
#### Description
Currently, Khiops scenarios's `MaxCoreNumber`, `MemoryLimit` and `TemporaryDirectoryName` `SystemParameters` are set either from a custom `GeneralOptions` instance, or from `KhiopsRunner`'s `general_options` attribute. But, the `GeneralOptions`'s attributes `max_cores`, `max_memory_mb` and `khiops_temp_dir` are initialized from `khiops_env` `KHIOPS_PROC_NUMBER`, `KHIOPS_MEMORY_LIMIT` and `KHIOPS_TMP_DIR` attributes, respectively.

However:
- `KHIOPS_PROC_NUMBER` is just an internal variable of `khiops_env` which is used for setting the `KHIOPS_MPI_COMMAND` variable; thus, this sets the upper bound of the number of CPU cores that Khiops would use in the current session;
- `KHIOPS_MEMORY_LIMIT` is relayed to the `MODL*` binaries and sets the upper bound of the number of MBs that Khiops would use in the current session;
- `KHIOPS_TMP_DIR` is relayed to the `MODL*` binaries and sets the default temporary directory that Khiops would use in the current session.

Hence, these are _global_ settings which set bounds for _any_ processing done by Khiops in the current working session.

However, Khiops scenarios' parameters `SystemParameters.{MaxCoreNumber,MemoryLimit,TemporaryDirecytoryName}` are _local_ to each processing (i.e. to each Core API call), hence:

- they should be set via the Khiops Core API calls
- the expectation is that their values are lower than or equal to the global settings.

#### Questions/Ideas
- All Khiops Core API functions defined in `khiops/core/api.py` should take three new keyword arguments:
   - `max_core_number: int`
   - `memory_limit: int`
   - `tmp_dir: str`
- the `KhiopsRunner._write_scenario_prologue` should not write into `AnalysisSpec.SystemParameters.{MaxCoreNumber,MemoryLimit,TemporaryDirectoryName}` from the `general_options` anymore, but from `task_args`, as these are "task"-level arguments.

**Comment by folmos-at-orange** [comment]
So, these parameters will be part of the official API ? Not only for Python ?

**Comment by folmos-at-orange** [comment]
One detail: When executing a large quantity small tasks is often convenient to execute with just 1 CPU because the overhead coming from the MPI process creation dominates the execution time. This overhead is worse on machines with many CPUs.

So when an API with `max_cores` set to 1 or 2 I think MPI should not be used on execution.

**Comment by popescu-v** [comment]
> So, these parameters will be part of the official API ? Not only for Python ?

I suppose so, as we need to be iso-functional with the Core GUI.

**Comment by popescu-v** [comment]
> One detail: When executing a large quantity small tasks is often convenient to execute with just 1 CPU because the overhead coming from the MPI process creation dominates the execution time. This overhead is worse on machines with many CPUs.
> 
> So when an API with `max_cores` set to 1 or 2 I think MPI should not be used on execution.

I see your point and the value in the proposal, but:
- in my understanding, this would diverge from the current functioning of Khiops Core: the `khiops` / `khiops_env` scripts do not parse the scenarios to be aware that only 1 or 2 CPUs were required;
- implementing this on the Python side would break the invariant of relying exlusively on `khiops_env` for handling the command construction logic.
Hence, it needs to be discussed.

**Comment by folmos-at-orange** [comment]
Ok for discuss. Another point, I'd go even further: some api calls do not need MPI (ex. `read_dictionary_file`) so the cpu number I think the CPU number should'n be available for them.

**Comment by popescu-v** [comment]
> Ok for discuss. Another point, I'd go even further: some api calls do not need MPI (ex. `read_dictionary_file`) so the cpu number I think the CPU number should'n be available for them.

Following discussion, the conclusions are:
- we keep the invariant of relying exclusively on `khiops_env` for handling execution logic; hence, if `KHIOPS_PROC_NUMBER` > 2, then `mpiexec` would be used, irrespective of what is specified at the scenario level (in terms of `MaxCores`); thusly, also the coherence with the Core GUI / batch behavior is kept;
- all Core API functions would get the three parameters (that would be passed to the scenarios), irrespective of whether MPI is actually needed or not; thus, this optimization would not be implemented (for the time being).

**Comment by popescu-v** [comment]
Support the user-defined scenario prologue through the same mechanism.
