### ISSUE TITLE
Remove `khiops_env`-Specific Attributes from the `KhiopsLocalRunner` Object

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#264]
#### Description
Currently, the `KhiopsLocalRunner` object maintains a set of attributes that are directly derived from `khiops_env`.
However, with a sole exception (see below), `khiops_env` should be a "black box" for the Khiops Python library.
Thus, most such attributes should be removed.

#### Questions/Ideas
- Specifically, the following attributes should be removed:
  - `max_cores`
  - `max_memory_mb`
  - `khiops_temp_dir`

- However, the `_khiops_path`, `_khiops_coclustering_path` and `_mpi_command_args` (to be renamed to `_khiops_mpi_command` to match `khiops_env` naming conventions) should be kept, as they are needed to compose, by concatenation, the full path to the Khiops command / to get the Khiops Coclustering command.

**Comment by folmos-at-orange** [comment]
It isn't enough to render them private ?
