### ISSUE TITLE
Support Pre-release Versions of Khiops Binary Packages

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#265]
#### Description
Currently, versions of the Khiops Python library can only have the form `x.y.z.p[-r]`, where:
- `x`, `y`, `z` are integers which specify the version of the upstream Khiops binary package
- `p` is integer
- `r` has the form `t.w`, where:
  - `t` is integer
  - `w` is string in the set `("a", "b", "rc")`

Hence, we can represent for example: `10.2.3.0-b.5`.

However, versions of the Khiops Python library that depend on pre-release versions of the Khiops binary package, e.g. `10.2.3-b.5` cannot be accurately designated. Indeed, we cannot use `10.2.3-b.5.0-b1` (or even `10.2.3-b.5.0` for that matter) as versions for the Khiops Python library. We are obliged to use versions like `10.2.3.0-b.5` to _suggest_ the link to the upstream `10.2.3-b.5` Khiops binary package version the Python library depends on.

#### Questions/Ideas
- The goal of this issue is to also support pre-release versions of the upstream Khiops binary package, e.g. version like: `10.2.3-b.5.0-b.1`, which means: "first beta version of the `.0` of the Khiops Python library which depends on the upstream fifth beta version of `10.2.3` Khiops binary package".
  - For Conda, which does not support hyphens in the versions, this kind of version would be `10.2.3b.5.0b.1`.
- To discuss whether this looks like a satisfactory alternative to the current state, which might lead to confusions when releases are based on pre-releases of the Khiops binary packages.

**Comment by folmos-at-orange** [comment]
Being in phase with the pre-release status of `khiops-core` adds too much complexity to the notation. This because we adapted semver (with a twist) with the extra increment. 

Usually there are not many pre-releases of `khiops-core` so suggesting compatibility only with the main three digits is enough.

**Comment by folmos-at-orange** [comment]
Also the suggestion for conda doesn't work:
```bash
> pep440 10.2.3b.5.0b.1
Version is not canonical according to Pep 440
```

**Comment by popescu-v** [comment]
> Also the suggestion for conda doesn't respect PEP440 which is used by Conda
> 
> ```shell
> > pep440 10.2.3b.5.0b.1
> Version is not canonical according to Pep 440
> ```

OK, correct. Hence, closing with "won't fix".
