### ISSUE TITLE
Narrow the scope of auto-execution of workflows

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#282]
#### Description
Currently, some workflows such as `unit-test.yml` execute even if the changes did not change any Python code. We should narrow their scope of execution.

#### Questions/Ideas
- `unit-test.yml`:
```yaml
pull_request:
    paths:
      khiops/**.py
      tests/**.py
      pykhiops/**.py
      .github/workflows/unit-tests.yml
```
- Apply also similar scopes to other relevant workflows.

**Comment by popescu-v** [comment]
Changes to the Docker files can also impact the execution of these workflows, but this is more difficult to detect IMHO (e.g. if the Docker image tag points to an updated image)...
