### ISSUE TITLE
Change pykhiops package name to khiops

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#29]
#### Description
With the coming conda packaging (which is called `khiops`) the naming `pykhiops` is put into question (mostly when importing)

#### Questions/Ideas
- We should have a smooth deprecation of `pykhiops`
- **All** documentation is potentially affected
- The repo name: `khiops-python` ?
- The pip name: `khiops` ?
  - Is there anyway to redirect a `pip install pykhiops` to a `pip install khiops`?

**Comment by popescu-v** [comment]
Well, it is always possible to create, in Conda and in Pip, a transient "metapackage" called `pykhiops`, which installs the `khiops` package behind the scenes, while issuing a deprecation warning upon install:

- in Conda, this can be driven via the `post-link` script,
- in Pip, this can be driven via `setup.py`, as we do a source install anyway.

I think it would be best to:

- have the package named `khiops` in both Conda and Pip environments
- have the package namespace called `khiops` as well, so that confusion is avoided; on a transient basis, `pykhiops` should be deprecated, i.e. still supported, with a deprecation warning issued when `pykhiops*` imports are done
- have the Git repo named `python-package` inside the `khiops` (GitLab.com) / `khiopsml` (GitHub) groups (see e.g. the XGBoost monorepo, where the Python package lives inside a `python-package` folder): https://github.com/dmlc/xgboost/tree/master/python-package. Contrary to XGBoost, in our case it is better IMHO to keep separate Git repos inside a single group.

**Comment by felipe-olmos-orange** [comment]
Implemented in #91
