### ISSUE TITLE
Implement a helper to download the sample datasets

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#30]
#### Description
*Maybe* in the future the sample datasets will not be available at install. Instead, they would be available in a website

#### Questions/Ideas
- Deprecate `get_samples_dir()` from `core.api` and the `PyKhiopsRunner` class
- Implement a function similar to that of scikit-learn to download the packages.
- Modify the samples and tutorials to use the new function

**Comment by felipe-olmos-orange** [comment]
Implemented in #106
