### ISSUE TITLE
Parameterize Conda Channel for `khiops-core` in `Dockerfile`s and `conda` Workflows

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#318]
#### Description
Currently, `khiops-dev` is hard-coded for these, which obliges us to push final `khiops-core` releases to `khiops-dev` as well.

#### Questions/Ideas
- The solution is to have this channel as an input to the `docker.yml` and `conda.yml` workflows. In the former case (Docker), this channel input would be passed as a build `ARG` to the `Dockerfile`s.

**Comment by folmos-at-orange** [comment]
Having all versions in `khiops-dev` was the intent. We do not want to pollute the download count in the main channel.

**Comment by popescu-v** [comment]
> Having all versions in `khiops-dev` was the intent. We do not want to pollute the download count in the main channel.
Yes, right, thanks for reminding this! Hence, I will reject the issue.

**Comment by popescu-v** [comment]
All CI / test versions should be taken from `khiops-dev` in order to keep `khiops` download statistics accurate.
