### ISSUE TITLE
Eliminate scenario system parameter prologue

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#32]
#### Description
Currently the system parameters number of processes, max memory and temporary file are passed as an scenario. It turns out that they can be passed with the environment.

#### Questions/Ideas
- Eliminate the prologue scenario code generation
- Make the runner set the correct environment variables in its setters
- The only prologue for the scenarios should be that of the user (advanced, usually for us)

**Comment by folmos-at-orange** [comment]
Rejected because it is a feature: Env vars limit scenario parameters and thus they are not redundant.
