### ISSUE TITLE
Optimize sklearn estimator serializations

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#38]
#### Description
Currently the serialization of sklearn estimators saves two times the learning reports: one as a Python object and another as a JSON object. This could be a problem for very large reports.

#### Questions/Ideas
- An ideal implementation:
  -  `__setstate__`: should mark the `.report_` attribute not to be serialized and let Python serialize the rest
  -  `__getstate__`: should build the `.report_` attribute from `.report_raw_`.

**Comment by folmos-at-orange** [comment]
Obsoleted with the new report object that saves the raw JSON.
