### ISSUE TITLE
Default unsupervised discretization and grouping methods are wrong

### ISSUE THREAD

**Issue by bruno-at-orange** [KhiopsML/khiops-python#4]
#### Description
In the method `pykhiops.core.api.train_predictor`, in case of unsupervised analysis, the default value of `discretization_method` is **MODL**. It should be **EqualWidth** (as it says in the documentation). 

We can see it line 52 of the scenario  [train_predictor_ri6v3geh._kh.txt](https://github.com/KhiopsML/khiops-python/files/11947417/train_predictor_ri6v3geh._kh.txt)

**Comment by marcboulle** [comment]
Cela provoque une segmentation fault dans Khiops, et c'est donc grave.
Il y a un bug pykhiops qui ne lance paramètre pas khiops correctement, et un bug khiops qui ne devrait pas planter (ce dernier bug est corrigé en V11, et ne sera pas patché en V10).

**Comment by marcboulle** [comment]
Same problem with the grouping method.

In the method pykhiops.core.api.train_predictor, in case of unsupervised analysis, the default value of grouper_method is MODL. It should be BasicGrouping (as it says in the documentation).

**Comment by felipe-olmos-orange** [comment]
Todo:
- Change the `khiops.core.api._run_task` method to change the discretization/grouping parameters differently when `target_variable == ""`

**Comment by folmos-at-orange** [comment]
Cannot reproduce.

Executing
```python
from os import path
import khiops.core as kh

# Set the file paths
dictionary_file_path = path.join(kh.get_runner().samples_dir, "Adult", "Adult.kdic")
data_table_path = path.join(kh.get_runner().samples_dir, "Adult", "Adult.txt")
results_dir = path.join("kh_samples", "train_predictor")

# Train the predictor
kh.train_predictor(
    dictionary_file_path,
    "Adult",
    data_table_path,
    "",
    results_dir,
    max_trees=0,
    trace=True,
)
```
Generates the following scenario (even in older version, and specifically the one that changed the behavior for which could have generated this bug)

```c
// System settings
AnalysisSpec.SystemParameters.MaxCoreNumber 10

// Scenario for task train_predictor
// Dictionary file and class settings
ClassManagement.OpenFile
ClassFileName /opt/khiops/samples/Adult/Adult.kdic
OK
ClassManagement.ClassName Adult

// Train/test database settings
TrainDatabase.DatabaseFiles.List.Key Adult
TrainDatabase.DatabaseFiles.DataTableName /opt/khiops/samples/Adult/Adult.txt
TrainDatabase.HeaderLineUsed true
TrainDatabase.FieldSeparator
TrainDatabase.DatabaseFormatDetector.DetectFileFormat
TrainDatabase.SampleNumberPercentage 70
TrainDatabase.SamplingMode Include sample
TrainDatabase.SelectionAttribute
TrainDatabase.SelectionValue
TrainDatabase.TestDatabaseSpecificationMode Complementary

// Target variable
AnalysisSpec.TargetAttributeName
AnalysisSpec.MainTargetModality

// Predictors to train
AnalysisSpec.PredictorsSpec.SelectiveNaiveBayesPredictor true
AnalysisSpec.PredictorsSpec.AdvancedSpec.UnivariatePredictorNumber 0

// Selective Naive Bayes settings
AnalysisSpec.PredictorsSpec.AdvancedSpec.InspectSelectiveNaiveBayesParameters
TrainParameters.MaxEvaluatedAttributeNumber 0
SelectionParameters.MaxSelectedAttributeNumber 0
Exit

// Feature engineering
AnalysisSpec.PredictorsSpec.ConstructionSpec.MaxTreeNumber 0
AnalysisSpec.PredictorsSpec.ConstructionSpec.MaxAttributePairNumber 0
AnalysisSpec.PredictorsSpec.AdvancedSpec.InspectAttributePairsParameters
AllAttributePairs true
Exit
AnalysisSpec.PredictorsSpec.ConstructionSpec.MaxConstructedAttributeNumber 100
AnalysisSpec.PredictorsSpec.AdvancedSpec.InspectConstructionDomain
Exit

// Data preparation (discretization & grouping) settings
AnalysisSpec.PreprocessingSpec.TargetGrouped false
AnalysisSpec.PreprocessingSpec.DiscretizerSpec.SupervisedMethodName EqualWidth
AnalysisSpec.PreprocessingSpec.DiscretizerSpec.UnsupervisedMethodName EqualWidth
AnalysisSpec.PreprocessingSpec.DiscretizerSpec.MinIntervalFrequency 0
AnalysisSpec.PreprocessingSpec.DiscretizerSpec.MaxIntervalNumber 0
AnalysisSpec.PreprocessingSpec.GrouperSpec.SupervisedMethodName BasicGrouping
AnalysisSpec.PreprocessingSpec.GrouperSpec.UnsupervisedMethodName BasicGrouping
AnalysisSpec.PreprocessingSpec.GrouperSpec.MinGroupFrequency 0
AnalysisSpec.PreprocessingSpec.GrouperSpec.MaxGroupNumber 0

// Output settings
AnalysisResults.ResultFilesDirectory ./kh_samples/train_predictor
AnalysisResults.ResultFilesPrefix

// Build model
ComputeStats

// End of scenario for task train_predictor

// Exit Khiops
ClassManagement.Quit
OK
```

**Comment by folmos-at-orange** [comment]
For better traceability in the future I will implement a "Khiops version" timestaming of scenarios.

**Comment by folmos-at-orange** [comment]
Reproduced the issue with the code
```python
from os import path
import khiops.core as kh

# Set the file paths
dictionary_file_path = path.join(kh.get_samples_dir(), "Adult", "Adult.kdic")
data_table_path = path.join(kh.get_samples_dir(), "Adult", "Adult.txt")
results_dir = path.join("kh_samples", "train_predictor")

# Train the predictor
kh.train_predictor(
    dictionary_file_path,
    "Adult",
    data_table_path,
    "",
    results_dir,
    max_trees=0,
    discretization_method="MODL",
    trace=True
)
```

**Comment by folmos-at-orange** [comment]
In addition to the changes above I added the reporting of the stdout if not empty

**Comment by marcboulle** [comment]
Est-ce qu'un simple assert python vérifiant que MODL n'est pas utilisé en non supervisé pourrait être une solution acceptable?
C'est une seule ligne de code, qu'il suffira d'enlever pour prendre en compte les évolution V11.

**Comment by folmos-at-orange** [comment]
Ok, but we'll have to mantain it until Khiops 12, since we always maintain the n-1 version.

**Comment by marcboulle** [comment]
Tu veux dire qu'il faut que l'assert soit conditionné par la version majeure 10?
Est-ce vraiment nécessaire, puisque quand on réinstalle pykhiops par conda, on réinstalle également les binaire de Khiops core?
Cela signifie en fait qu'en V10, pykhiops a un patch qui contourne le big de Khiops core, et qu'avec Khiops core V11, ce patch n'est plus nécessaire?

**Comment by folmos-at-orange** [comment]
> Tu veux dire qu'il faut que l'assert soit conditionné par la version majeure 10?

Yes. But the check code will be there until Khiops 12 since in Khiops 11 we'll support Khiops 10 as well. Maybe I'm mistaken ?

By the way I implemented this as a user exception (`ValueError`) since it is not an "internal" programming error.

> Est-ce vraiment nécessaire, puisque quand on réinstalle pykhiops par conda, on réinstalle également les binaires de Khiops core?

Indeed, but we still support pip + khiops system-wide install so we cannot assume that the versions will match.

> Cela signifie en fait qu'en V10, pykhiops a un patch qui contourne le big de Khiops core, et qu'avec Khiops core V11, ce patch n'est plus nécessaire?

I think so. What means is that the code to check this particular input will have to stay until Khiops 12 when we drop the support for Khiops 10.

**Comment by marcboulle** [comment]
Ok: j'avais effectivement uniquement le cas conda en tête
C'est l'installation avec pip qui impose cette contrainte d'attendre la V12: merci pour la clarification
