### ISSUE TITLE
Add sklearn estimator attributes

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#49]
#### Description
Sklearn estimators have a number of standard attributes (eg `classes_`, `n_features_in_`) and we should implement them so to be the closer to their standard.

#### Questions/Ideas
- Some of the attributes are straight forward but others no: What to do with `n_features_in_` in the multi-table case?
- Think about what Khiops-specific attributes to add:
   - `n_preprocessed_features`, `levels_`, `n_selected_features_`, `weights_`, `importances_`.
   - Any other?
- Do not forget to document in the classes' docstrings.

**Comment by popescu-v** [comment]
See also #75

**Comment by nairbenrekia** [comment]
From a discussion with Felipe (3rd of May):

1) For `Khiops Classifier`, the following features will be added:
    - `n_classes_` : number of classes.
    - `n_features_built_` : number of the evaluated features.
    - `features_built_names_`: names of the evaluated features.
    - `features_built_importances_` : level of the evaluated features (numpy table).
    - `n_features_used_`: number of the features selected by SNB.
    - `feature_used_names_`: names of the features selected by SNB.
    - `Feature_used_importances_`: Importance, Weight and Level of the features selected by SNB (numpy table).

2) For `Khiops Regressor`, the same features will be added except (obviously) `n_classes_`.

3) For `Khiops Encoder`, the following features will be added:
    - `n_features_built_` : number of the evaluated features.
    - `features_built_names_`: names of the evaluated features.
    - `features_built_importances_` : level of the evaluated features (numpy table).
