### ISSUE TITLE
Implement a sklearn helper to split multi-table datasets

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#51]
#### Description
The code splitting multi-table datasets is rather repetitive and it could be encapsulated into a function.

#### Questions/Ideas
- Use the `dict` dataset input and the `test_train_split` function to implement it. Internally use the dataset.
- What is the return value? 2-tuple of lists? 2-tuple of `dict` datasets?

**Comment by folmos-at-orange** [comment]
Unblocked when #158

**Comment by folmos-at-orange** [comment]
Obsoleted by #180
