### ISSUE TITLE
Implement helper to create multi-table dictionaries

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#52]
#### Descriptions
Implement in `core.helpers` a function to create multi table dictionaries. 

#### Questions/Ideas
- The prototype could be inspired of that of the `Dataset` class of `pykhiops.sklearn`
  - Maybe we could use this function as a base for the implementation in `sklearn`?

**Comment by folmos-at-orange** [comment]
Wait for #158

**Comment by popescu-v** [comment]
Subsumed by https://github.com/KhiopsML/khiops-python/issues/182
