### ISSUE TITLE
Create a dimensionality reduction enrichment function

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#55]
This function takes a multi-table dataset and clusterize the secondary table variables and then adds them to the secondary table.

The methods returns the enriched dictionary file path.

![enrichment](/uploads/0f94b94d2b26860bc98ac2ae23facaee/enrichment.PNG)

**Comment by folmos-at-orange** [comment]
Will be obsoleted when the new _instance-variable_ coclustering algorithm will be available.
