### ISSUE TITLE
Improve pykhiops.sklearn documentation

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#56]
Namely:
- show how `khiops.sklearn`  can be used in sklearn pipelines which use other sklearn facilities (preprocessing, other estimators, vote between several estimators, etc)
- show examples where Khiops would refrain from building a model, thus providing strong hints that a model cannot be learnt from the data, while other estimators would overfit by e.g. laborious hyperparameter tuning.

**Comment by folmos-at-orange** [comment]
Obsoleted by khiops.org and tutorials.
