### ISSUE TITLE
Implement automatic sort in core functions

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#58]
#### Implementation ideas
- Add a flag `sort` to `train_predictor`, `deploy_model`, `train_recoder`, `evaluate_predictor` (default `False`)
- Traverse the tables to generate the scenario code to be executed before training
- Modify `sklearn` estimators to just use the new `sort` option of `core` functions and eliminate calls to `core.sort_data_table`

**Comment by popescu-v** [comment]
Maybe just implement a helper function `sort_dataset` that takes a dictionary file or domain and sorts all tables by their key. The signature would be similar to that of `train_predictor`.

**Comment by folmos-at-orange** [comment]
The automatic sort for the `sklearn` module was implemented in the `10.1.1`
