### ISSUE TITLE
Add a Windows Docker in CI/CD

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#64]
2/7/2022: In stand by because of dependencies

### Implementation Ideas
- Use a [Windows Runner] (it comes with Python)
- Download the Khiops Windows App from the Artifactory (not available yet)
- Download Sci-kit learn
- Run `test_samples.py` with `unittests`

**Comment by felipe-olmos-orange** [comment]
This was relevant for GitLab. In github we have native windows runners and the PR #91 implements testing on those.
