### ISSUE TITLE
Harmonize documentation with the new Khiops Site

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#73]
#### Description
The new Khiops website will have a remake of its documentation. This site contain all documentation including pyKhiops' but will be probably not "harmonic" with the current version of our documentation. So an harmonization will be necessary.

#### Questions/Ideas
- We should wait for a first release of the new documentation site.
- The default and easiest technical solution is just point to the current site.
 - This entails a visual harmonization 
- Related to #185 because the new site uses MkDocs
 - Should we migrate to MkDocs ????
 - This entails an study because we will probably lose functionality.
 - See MkDocstrings
- In anycase a content harmonization is necessary and probably add more introductory material in the context of the new documenation.

**Comment by felipe-olmos-orange** [comment]
Done in #105

We stayed with Sphinx and now store the documentation in https://khiopsml.github.io/khiops-python. The khiops.org site points the API docs there.

I  did some harmonization but the theme largely is the same as before. I also tried [Material for Sphinx](https://bashtage.github.io/sphinx-material/) but it is very limited (in colors mostly) and I could not reproduce the style of khiops.org. We'll give a try if it matures in future versions.
