### ISSUE TITLE
Save the sklearn training report even if there is no model

### ISSUE THREAD

**Issue by popescu-v** [KhiopsML/khiops-python#85]
#### Description
Both Khiops Modeling and ~~Khiops Coclustering~~ can return an empty model. In those cases the corresponding estimator should be in "non fitted" state but the reports should be available.

**Comment by felipe-olmos-orange** [comment]
We should revise this. For complying with the sklearn standards #87 we should deprecate `_is_fitted` as sklearn `check_is_fitted` method considers an estimator fitted has any attributes set.

We could have a property `last_report` or similar to treat this case.

**Comment by popescu-v** [comment]
We can follow sklearn conventions: if attributes defined, then estimator is fitted, then the report is parsed. Otherwise, it is not.
